### ISSUE TITLE
How to install it?

### ISSUE THREAD

**Issue by yvasyliev** [ruriko123/Reddit-video-downloader-extension#1]
Hi,

Could you please add Installation guidelines to README.md?

Thanks. 😊

**Comment by Lekhak123** [comment]
Hey,

You can refer to [this article ](https://dev.to/ben/how-to-install-chrome-extensions-manually-from-github-1612) to install this extension.

**Comment by Lekhak123** [comment]
It seems like the recent reddit api changes have made this program unusable. I will try to fix all the breaking changes within a week.

**Comment by yvasyliev** [comment]
> Hey,
> 
> You can refer to [this article ](https://dev.to/ben/how-to-install-chrome-extensions-manually-from-github-1612) to install this extension.

I'm not sure what file extension Chrome is expecting as `.zip` is not visible...
![image](https://github.com/ruriko123/Reddit-video-downloader-extension/assets/44120348/45c23d72-a4d6-4524-99fe-abf3b0786d48)

**Comment by Lekhak123** [comment]
You can directly go inside the folder with the extension files (in this case, the folder called "Reddit-video-downloader-extension") and click on "Select Folder". It doesn't have to be a .zip file. 

I have updated the code for this extension just now. Make sure to go ahead and download the files to this extension again.  :) The extension should work properly. Let me know if there are any more issues.

**Comment by Lekhak123** [comment]
I am closing this issue since I think that there aren't any more problems with this issue.

**Comment by yvasyliev** [comment]
Got it!

That's an awesome extension dude 🫡

**Comment by Lekhak123** [comment]
Let me know if you encounter any more issues.
